using MedLoop.NextGen.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MedLoop.NextGen.Services;

// The legacy app carried five separate PDF libraries (iTextSharp, ABCpdf,
// Aspose.PDF, Ghostscript.NET, Rotativa) — of which only iTextSharp was
// ever actually invoked anywhere; the other four were dead weight, two of
// them (ABCpdf, Aspose.PDF) commercially licensed. QuestPDF is the only PDF
// dependency here.
//
// Licensing note, for whoever maintains this: QuestPDF's free "Community"
// license only covers organizations with less than $1M USD in annual gross
// revenue (or non-profits/open source). Confirm MedLoop's eligibility
// before shipping this to production — if not eligible, a commercial
// QuestPDF license is required. This is exactly the kind of licensing
// question the legacy app's audit flagged for iTextSharp (AGPL) and never
// resolved; don't repeat that here by assuming "free" without checking.
public class QuestPdfInvoiceService : IInvoiceService
{
    public byte[] GenerateOrderInvoice(Order order)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(column =>
                {
                    column.Item().Text("MedLoop — B2B Order Invoice").FontSize(18).Bold();
                    column.Item().Text($"Order #{order.Id}").FontSize(10);
                    column.Item().Text($"Date: {order.CreatedAt:yyyy-MM-dd HH:mm} UTC").FontSize(10);
                });

                page.Content().Column(column =>
                {
                    column.Spacing(12);

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Seller").Bold();
                            c.Item().Text(order.SellerPharmacy?.Name ?? order.SellerPharmacyId);
                            c.Item().Text(order.SellerPharmacy?.Address ?? string.Empty);
                        });

                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Buyer").Bold();
                            c.Item().Text(order.BuyerPharmacy?.Name ?? order.BuyerPharmacyId);
                            c.Item().Text(order.BuyerPharmacy?.Address ?? string.Empty);
                        });
                    });

                    column.Item().LineHorizontal(1);

                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Unit Price").Bold();
                            header.Cell().Text("Subtotal").Bold();
                        });

                        table.Cell().Text(order.Product?.Name ?? order.ProductId);
                        table.Cell().Text(order.Quantity.ToString());
                        table.Cell().Text(order.UnitPrice.ToString("C"));
                        table.Cell().Text((order.Quantity * order.UnitPrice).ToString("C"));
                    });

                    column.Item().AlignRight().Column(c =>
                    {
                        c.Item().Text($"Platform fee ({order.PlatformFeeRate:P1}): {order.PlatformFeeAmount:C}");
                        c.Item().Text($"Total: {order.TotalAmount:C}").Bold().FontSize(14);
                    });

                    column.Item().Text($"Payment reference: {order.PaymentReference}").FontSize(9);
                    column.Item().Text($"Status: {order.Status}").FontSize(9);
                });

                page.Footer().AlignCenter().Text("Generated by MedLoop NextGen — this is a system-generated document.").FontSize(8);
            });
        });

        return document.GeneratePdf();
    }
}
